# Generated by Django 2.1.1 on 2018-09-28 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumeroIdentificador', models.PositiveSmallIntegerField()),
                ('TipoComentario', models.BooleanField(default=True)),
                ('Mensaje', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreProyecto', models.CharField(max_length=35)),
                ('Descripcion', models.CharField(max_length=35)),
                ('Fecha', models.DateTimeField(auto_now_add=True)),
                ('LenguajeProgramacion', models.CharField(choices=[('JAVA', 'JAVA-SWING'), ('C', 'VISUAL-STUDIO')], default='JAVA', max_length=4)),
            ],
        ),
    ]
